### ISSUE TITLE
LRAPA colocated sensors

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/reports#1]
Have a look at the Lane County (Eugene, Oregon area) Air Protection Agency — LRAPA.

The have deployed a network of Purple Air sensors and have intentionally colocated some with regulatory monitors. I believe their sensors are identified with “LRAPA” in their labels in the ‘pas’ object.

You can create a new OR/LRAPA/ subdirectory in the reports repository and begin investigating the following:

1. How many monitors and how many sensors area in the LRAPA area?
2. How many sensors are colocated with FRM monitors?
3. For the best colocated sensor, look at the ‘pat’ data and decide whether it is reasonable.
4. Process the ‘pat’ data into ‘airsensor’ objects using QC_00 if necessary to retain as much data as is reasonable.
5. Use the R lm() function to calculate linear fits of ‘airsensor’ object PM2.5 to ‘monitor’ PM2.5. Do this for one weeks worth of data in each of July, August, September and October.
6. See if the model fit parameters differ.
7. Now see if you can figure out how to access the hourly aggregated humidity data and then run a multi-variate fit using both PM2.5 and humidity from the sensor.
8. Do the model fit parameters change when you add humidity?

**Comment by AstridSanna** [comment]
WIP 
I finally decided to use a radius of 500 m. 
I created a local archive of pat files so that I can use the airsensor fucntions more easily.
